
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.modelolenguaje.Gramatica;

/** CUP generated class containing symbol constants. */
public class ParserBugSym {
  /* terminals */
  public static final int MAQ = 17;
  public static final int POT = 15;
  public static final int CHAR = 8;
  public static final int MAI = 19;
  public static final int UMINUS = 16;
  public static final int ENTERO = 36;
  public static final int XOR = 23;
  public static final int DOUBLE = 5;
  public static final int INT = 4;
  public static final int FOR = 43;
  public static final int NOT = 24;
  public static final int SEMICOLON = 34;
  public static final int AND = 21;
  public static final int CARACTER = 39;
  public static final int OR = 22;
  public static final int BOOL = 6;
  public static final int DIV = 13;
  public static final int IF = 45;
  public static final int ID = 42;
  public static final int DECIMAL = 37;
  public static final int EOF = 0;
  public static final int EQUAL = 26;
  public static final int TRUE = 40;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MUL = 12;
  public static final int CADENA = 38;
  public static final int DIF = 27;
  public static final int MENOS = 11;
  public static final int PAR_C = 29;
  public static final int MOD = 14;
  public static final int PAR_A = 28;
  public static final int VOID = 9;
  public static final int ERROR = 2;
  public static final int LL_C = 33;
  public static final int MEQ = 18;
  public static final int LL_A = 32;
  public static final int WHILE = 44;
  public static final int MEI = 20;
  public static final int STRING = 7;
  public static final int COR_C = 31;
  public static final int INCER = 25;
  public static final int FALSE = 41;
  public static final int COR_A = 30;
  public static final int PRINT = 3;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "PRINT",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CHAR",
  "VOID",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "MOD",
  "POT",
  "UMINUS",
  "MAQ",
  "MEQ",
  "MAI",
  "MEI",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "INCER",
  "EQUAL",
  "DIF",
  "PAR_A",
  "PAR_C",
  "COR_A",
  "COR_C",
  "LL_A",
  "LL_C",
  "SEMICOLON",
  "COMA",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CARACTER",
  "TRUE",
  "FALSE",
  "ID",
  "FOR",
  "WHILE",
  "IF"
  };
}

