
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.modelolenguaje.Gramatica;

/** CUP generated class containing symbol constants. */
public class ParserBugSym {
  /* terminals */
  public static final int MAQ = 20;
  public static final int POT = 18;
  public static final int CHAR = 11;
  public static final int MAI = 22;
  public static final int UMINUS = 19;
  public static final int ENTERO = 44;
  public static final int XOR = 26;
  public static final int DOUBLE = 8;
  public static final int SUMAR = 32;
  public static final int INT = 7;
  public static final int FOR = 51;
  public static final int SEMICOLON = 40;
  public static final int NOT = 27;
  public static final int AND = 24;
  public static final int CARACTER = 47;
  public static final int OR = 25;
  public static final int BOOL = 9;
  public static final int DDOT = 43;
  public static final int REFFILE = 5;
  public static final int DIV = 16;
  public static final int CONTINUAR = 56;
  public static final int IF = 53;
  public static final int IMPORTAR = 4;
  public static final int ID = 50;
  public static final int DOT = 42;
  public static final int DECIMAL = 45;
  public static final int EOF = 0;
  public static final int RETURN = 55;
  public static final int EQUAL = 29;
  public static final int TRUE = 48;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int MUL = 15;
  public static final int CADENA = 46;
  public static final int DIF = 30;
  public static final int MENOS = 14;
  public static final int PAR_C = 35;
  public static final int MOD = 17;
  public static final int BREAK = 57;
  public static final int PAR_A = 34;
  public static final int VOID = 12;
  public static final int EQ = 31;
  public static final int ERROR = 2;
  public static final int LL_C = 39;
  public static final int ELSE = 54;
  public static final int LL_A = 38;
  public static final int RESTAR = 33;
  public static final int MEQ = 21;
  public static final int WHILE = 52;
  public static final int MEI = 23;
  public static final int STRING = 10;
  public static final int COR_C = 37;
  public static final int INCER = 28;
  public static final int FALSE = 49;
  public static final int COR_A = 36;
  public static final int PRINT = 3;
  public static final int INCERTEZA = 6;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "PRINT",
  "IMPORTAR",
  "REFFILE",
  "INCERTEZA",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CHAR",
  "VOID",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "MOD",
  "POT",
  "UMINUS",
  "MAQ",
  "MEQ",
  "MAI",
  "MEI",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "INCER",
  "EQUAL",
  "DIF",
  "EQ",
  "SUMAR",
  "RESTAR",
  "PAR_A",
  "PAR_C",
  "COR_A",
  "COR_C",
  "LL_A",
  "LL_C",
  "SEMICOLON",
  "COMA",
  "DOT",
  "DDOT",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CARACTER",
  "TRUE",
  "FALSE",
  "ID",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "CONTINUAR",
  "BREAK"
  };
}

